### ISSUE TITLE
Wasm todo

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#1127]
This is a list of thing we need to implement for Wasm MVP
- [x] Br yielding values #1111
- [x] I32Popcnt
- [x] F32Min/Max #659
- [x] Trunc JIT
- [x] Nearest JIT
- [x] Int64 (@Cellule #1806)
- [x] Unreachable operator
- [x] Unreachable state
- [ ] Missing OpCodes
  - [x] current_memory (0x3b)
  - [ ] grow_memory (0x39) (@MikeHolman)
  - [x] f64.copysign (0x91)
  - [ ] i32.trunc_u/f32 (0x9f) (@Krovatkin #1812)
  - [ ] i32.trunc_u/f64 (0xa0) (@Krovatkin #1812)
  - [ ] f32.convert_u/i32 (0xa9) (@Krovatkin)
  - [x] f32.reinterpret/i32 (0xad) (@Krovatkin #1813)
  - [x] get_global (0xbb)
  - [x] set_global (0xbc)
  - [ ] Int64 Conversions
    - [ ] i64.trunc_s/f32
    - [ ] i64.trunc_s/f64
    - [ ] i64.trunc_u/f32
    - [ ] i64.trunc_u/f64
    - [ ] i64.extend_s/i32 (@meg-gupta)
    - [ ] i64.extend_u/i32 (@meg-gupta)
    - [ ] f32.convert_s/i64
    - [ ] f32.convert_u/i64
    - [ ] f64.convert_s/i64
    - [ ] f64.convert_u/i64
    - [ ] f64.reinterpret/i64 (@arunetm)
    - [ ] i64.reinterpret/f64 (@arunetm)
- [x] [Globals](https://github.com/WebAssembly/design/blob/binary_0xc/BinaryEncoding.md#global-section)
- [ ] [Init Expressions](https://github.com/WebAssembly/design/blob/binary_0xc/BinaryEncoding.md#init_expr) 
  - [ ] For element segments' [offset](https://github.com/WebAssembly/design/blob/binary_0xc/BinaryEncoding.md#element-section) (@arunetm)
  - [x] For data segments' [offset](https://github.com/WebAssembly/design/blob/binary_0xc/BinaryEncoding.md#data-section)
  - [x] For globals' [initial value](https://github.com/WebAssembly/design/blob/binary_0xc/BinaryEncoding.md#global-entry)
- [ ] Correctly call imported functions from the function table (intermediary function used for the conversion) (@Cellule #1807)
- [ ] [Import types](https://github.com/WebAssembly/design/blob/binary_0xc/BinaryEncoding.md#import-entry)
  - [ ] Kind: Table
  - [ ] Kind: Memory (@MikeHolman)
  - [x] Kind: Global
- [ ] [Export types](https://github.com/WebAssembly/design/blob/binary_0xc/BinaryEncoding.md#export-entry)
  - [ ] Kind: Table
  - [x] Kind: Global
- [ ] Runtime Traps
  - [ ] Array access out of bound (@meg-gupta)
  - [ ] Verify [math trapping](https://github.com/WebAssembly/design/blob/binary_0xc/AstSemantics.md#32-bit-integer-operators)
  - [ ] Trap on invalid indirect call (out of bounds and invalid signature)
- [ ] Spec compliant
- [ ] Ignore the names section until we have use of it (@cellule #1855)
- [ ] Copy the binary buffer to prevent modification after call to `wasm.instantiateModule()` or `new WebAssembly.Module()` (@Cellule #1808)
- [x] 0xD format (@Cellule #1822)
  - [x] [OpCode Reordering](https://github.com/WebAssembly/design/blob/binary_0xd/BinaryEncoding.md#function-bodies)
  - [x] [Negative type constructors](https://github.com/WebAssembly/design/blob/binary_0xd/BinaryEncoding.md#language-types)
  - [x] [Block signature has byte -0x40 for no return value](https://github.com/WebAssembly/design/blob/binary_0xd/BinaryEncoding.md#block_type)
- [x] Enable deferred parsing by default
- [ ] Investigate Debugging/Profiling scenario on Edge
- [ ] Implement final Javascript API (@MikeHolman)
  - [ ] Remove `Wasm` Object from the global scope #1834
- [x] Retire WebAssembly branch completely (all dev work done in master)
- [ ] Security analysis (@Penguinwizzard)
- [ ] Known Bug Fixes
  - [ ] Assert on `print(Wasm.instantiateModule(buffer, ffi).exports.a);`
- [ ] Call import with int64 and float32 in arguments
- [ ] Performance
  - [ ] Use 4G array to detect out of bounds access and trap
  - [ ] Fold const math operations (#1852)

**Comment by liminzhu** [comment]
Good list for tracking. Can we add debugging there as well?

**Comment by Cellule** [comment]
This is more to track what is missing to be spec compliant.
Debugging is, in my opinion, an extra feature that we need to look into

**Comment by liminzhu** [comment]
Yeah I agree.

**Comment by commonlisp** [comment]
f32min/max is done.

**Comment by commonlisp** [comment]
trunc and nearest done.

**Comment by Krovatkin** [comment]
@Cellule PR #1514 adds `current_memory` and we also got a working version of `unreachable_operator` Should be able to open a PR shortly.

**Comment by Cellule** [comment]
Updated the list with everything I know we still needs to do for MVP
@LouisLaf for visibility

**Comment by Krovatkin** [comment]
@Cellule, fyi @MikeHolman 

a small update,

* redid globals. i should be able to open a PR as soon as we make sure it doesnt have any obvious goofs :-) 
*  finishing up with 

> i32.trunc_u/f32 (0x9f)
> i32.trunc_u/f64 (0xa0)
> i32.trunc_s/f64 (0xa0) //needs to throw an overflow exception
> i32.trunc_s/f64 (0xa0) //needs to throw an overflow exception

**Comment by Krovatkin** [comment]
@Cellule hey do you know if anyone is implementing **f32.reinterpret/i32**? if not, i think it's perfect for my afternoon pastime :-)

**Comment by Krovatkin** [comment]
@Cellule  oops, i take that back :-)  im sry. it looks the only thing that was missing is `Reinterpret_ITF` -> `Reinterpret_Prim` in IRBuilderAsmJs :-)

**Comment by MikeHolman** [comment]
I'm working on adding new JS API. In particular so far have implemented (or partially implemented)
WebAssembly.compile, WebAssembly.Module, WebAssembly.Instance, WebAssembly.RuntimeError, WebAssembly.CompileError

**Comment by Cellule** [comment]
Closed in favor https://github.com/Microsoft/ChakraCore/projects/1 for tracking
