### ISSUE TITLE
WebAssembly pre-v1.0 update

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#440]
The WebAssembly spec changed quite a bit recently and we have to update our implementation.
This is a list of things to do

- [x] : Add `Wasm` Object to the global object (#430)
- [x] : Add `instantiateModule` method to the `Wasm` Object. (In review #486 + #430) 
  - Takes 2 arguments
    - TypedArrayView with the bytes representing the wasm module
    - An Object representing the imports
- [x] : Modules return an `exports` (#452)
  - `var m = Wasm.instantiateModule(buf, imports); m.exports.foo();`
- [x] : Wasm magic number + version. [Module Header](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#high-level-structure) (#448)
- [x] : Use LEB128 for module offsets and indexes (#477)
- [x] : Page count for memory section instead of size (In Review #446) [Memory Section](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#memory-section)
- [x] : String for section instead of id. [Section Definition](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#high-level-structure) (#448)
- [x] : Fixed order of section (#481)
  - We can assume the section will be in the order represented in the BinaryEncoding document, however we don't *have* to validate it for the time being (later work order).
- [x] : Export table. (#489) [Export Table Section](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#export-table-section)
- [x] : Import table. [Import Table Section](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#import-table-section) (@commonlisp)
  - [x] : Two level import
- [x] : Rename `tableswitch` to `br_table` (#407)
  - [x] : `br_table` changes (@MikeHolman)
- [x] : Split functions section into decls and definitions sections (#481 + #477) (https://github.com/WebAssembly/design/pull/591)
- [x] : Signed LEB128 for i32.const and i64.const (@commonlisp is this done ?) (https://github.com/WebAssembly/design/pull/592)
- [ ] : Data Segments section (In Review: #439)
  - [ ] : Inline data segments (https://github.com/WebAssembly/design/pull/590)
- [x] : Memory in exports object `module.exports.memory`

**Comment by Cellule** [comment]
@commonlisp Can you mark which item you'll be working on?

**Comment by commonlisp** [comment]
[ ]: Add  Wasm  Object to the global object (In Review: #430)
[ ] : Add  instantiateModule  method to the  Wasm  Object. (In Review: #430) ◦Takes 2 arguments ◾ArrayBuffer with the bytes representing the wasm module
◾An Object representing the imports


[ X ] : Modules return an  exports  ◦ var m = Wasm.instantiateModule(buf, imports); m.exports.foo(); (In Review: #452)

[ X ] : Wasm magic number + version. Module Header (#448)
[ ] : Use LEB128 for module offsets and indexes (waiting on #448 to make PR but otherwise it is implemented)
 : Page count for memory section instead of size (In Review #446) Memory Section 
[ X ] : String for section instead of id. Section Definition  (#448)
[ ] : Fixed order of section ◦We can assume the section will be in the order represented in the BinaryEncoding document, however we don't have to validate it for the time being (later work order).

[ ] : Export table. Export Table Section 
[ X ] : Import table. Import Table Section (waiting on #448 to make PR but otherwise it is implemented)
 : Rename  tableswitch  to  br_table  (#407)
[ ] : Split functions section into decls and definitions sections (waiting on https://github.com/WebAssembly/design/pull/591)
[ ] : Arities in call, return and break
[ X ] : Signed LEB128 for i32.const and i64.const (waiting to make PR but otherwise it is implemented)

**Comment by Cellule** [comment]
@MikeHolman @commonlisp 
Could you guys comment here to update what you are working on.
I am working on updating instantiateModule to use TypedArray instead of ArrayBuffer

**Comment by MikeHolman** [comment]
Right now working on fixing up parsing function bodies, currently parsing of br_table. There were some discrepancies between our implementation and the spec. should be able to have pr out soon.

**Comment by Cellule** [comment]
PR #486 makes the change to the instantiateModule method

**Comment by Cellule** [comment]
I will do the `Memory in exports object` item

**Comment by Cellule** [comment]
I will look into the Export Table

**Comment by commonlisp** [comment]
Modules return an exports (#452) is merged. Both LEB128 items and part of split functions section (Names Section remaining but do we need it?) are merged #477. PR #487 for decoding import table. Exports namespace merged.

**Comment by commonlisp** [comment]
Heh, I had memory in exports object before but then I rolled it back since it wasn't specified. Guess we'll go back to that.

**Comment by Cellule** [comment]
Well apparently @MikeHolman already added the memory to the exports object

**Comment by Cellule** [comment]
I will look into the Indirect function calls

**Comment by commonlisp** [comment]
Inline data segments is done. Signed LEB128 for i32.const and i64.const is done.

**Comment by commonlisp** [comment]
Actually, it seems that we don't have i64.const at all right now, so signed LEB128 is only for i32.const though it is ready for i64.const. Was the i64 register implementation resolved?

**Comment by Cellule** [comment]
@commonlisp we don't have an implementation for i64 in the backend now. We don't need it in the near future however. I'll mark this work item as closed and we'll probably have a bigger work item for int 64 in the future

**Comment by commonlisp** [comment]
I'll work on testing and Names section unless there is something more pressing.

**Comment by commonlisp** [comment]
I have the Names Section ready but will defer the PR until after things settle.

**Comment by commonlisp** [comment]
Names Section is in PR #562 which implements the current design. If and when design PR #596 is accepted, we can revise.
